### ISSUE TITLE
Machines and stream processing at BFPG

### ISSUE THREAD

**Issue by runarorama** [runarorama/runarorama.github.com#4]

**Comment by aavogt** [comment]
Hi the dropbox link doesn't work anymore. It is referenced from http://hackage.haskell.org/package/machines-0.6.3

**Comment by cscalfani** [comment]
+1

**Comment by runarorama** [comment]
Fixed. Thanks!

**Comment by cscalfani** [comment]
I'm still getting an error. Here is the URL: https://dl.dropboxusercontent.com/u/4588997/Machines.pdf
